# Generated by Django 4.1.6 on 2023-02-12 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudentApp', '0006_artist_song'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='univstudent',
            name='user',
        ),
        migrations.DeleteModel(
            name='Artist',
        ),
        migrations.DeleteModel(
            name='Song',
        ),
        migrations.DeleteModel(
            name='UnivStudent',
        ),
    ]
